### PR TITLE
Keep reference to implementation pointer in blockInfo instead of block itself to fix block retaining leak

### PR DESCRIPTION
**Pull request by bounin**
Synopsis:
Check strong referenced object inside block and it is never released:

``` objective-c
AnyClass * obj = [AnyClass new]
[alertView respondsToSelector:@selector(alertView:didDismissWithButtonIndex:) withKey:nil usingBlock:^(id receiver, UIAlertView *alertView, NSInteger buttonIndex) {
     //// to capture obj
     NSLog (@"%@", obj);
}];
```

Problem:
_imp_implementationWithBlock()_ retains block so expression `imp_removeBlock(imp_implementationWithBlock(block))` just keeps retaining count by retaining and releasing block. (CFRetainCount **always returns 1 for block objects**). Similar you create extra reference for every superblock when you call (imp_implementationWithBlock(block) in _supermethodOfCurrentBlock_ method

Solution:
It is better to keep created block implementation pointer  in blockInfo dictionary instead of block itself. And use it later when releasing or returning superblock implementation.

After you apply new implementation obj variable from code above released after alertView disappears and released.

### CODE REVIEW

**Comment by zuccoi** [comment]
Thank you for your pull requests.

But, I can't reproduce your problem. I modified `-[iREViewController changeBackgroundColorAction:]` like below, then checked living memory using Instruments, but all UIAlertView instances were released. Can you provide me something to reproduce the problem?

&lt;iREViewController.m [REKit 1.0.0]&gt;

``` objective-c
- (IBAction)changeBackgroundColorAction:(id)sender
{
    // Get me
    __weak typeof(self) me = self;

    // Make obj
    NSDictionary *obj;
    obj = [NSDictionary new];

    // Show alertView
    UIAlertView *alertView;
    NSString *title;
    NSString *message;
    title = @"Change Background Color?";
    message = @"This alert view's delegate method is implemented using REReponder feature. And if you tap \"OK\" button, label will be updated using REObserver feature.";
    alertView = [[UIAlertView alloc] initWithTitle:title message:message delegate:nil cancelButtonTitle:@"Cancel" otherButtonTitles:@"OK", nil];
    [alertView respondsToSelector:@selector(alertView:didDismissWithButtonIndex:) withKey:nil usingBlock:^(id receiver, UIAlertView *alertView, NSInteger buttonIndex) {
        // Log obj
        NSLog(@"obj = %@", obj);

        // Cancel
        if (buttonIndex == 0) {
            return;
        }

        // Change backgroundColor
        float (^random)() = ^{
            return (arc4random() % 11) / 10.0f;
        };
        me.view.backgroundColor = [UIColor colorWithRed:random() green:random() blue:random() alpha:1.0f];
    }];
    alertView.delegate = alertView;
    [alertView show];
}
```

**Comment by bounin** [comment]
Of course UIAlertView instance released, but block along with all captured objects not released. Check if <b>obj</b> is released. To reproduce it let's modify the code above little bit:

 Add some test class to your project:

``` objective-c
@interface TestClass : NSObject @end
@implementation TestClass
-(void)dealloc {
    NSLog (@"TestClass object(%@) deallocated", self);
}
@end
```

Then instead of NSDictionary for object instantiation use TestClass in your code snippet above

``` objective-c
TestClass * obj;
obj = [TestClass new];
```

Now after you dismiss alert view you should see the corresponding record in debug console about TestClass deallocation. But it is not there if you not correctly keep tracking of implementation pointers for block objects returned by <b>imp_implementationWIthBlock(block)</b>, using it when need superblock and then releasing corresponding block by calling <b>imp_removeBlock(imp)</b> later on. I tested this on iOS device as well as in iOS simulator.

Thanks

**Comment by zuccoi** [comment]
Now I understand the problem. It's serious. I had fix it. But the way is different from yours. Please see diff from 4f6c2a89be520fb3e132b3c8c616c5558676aec8 to 4f6c2a89be520fb3e132b3c8c616c5558676aec8. I still manages block with blockInfo, because I think it's straightforward and powerful than IMP (block is object, and block is object user passed).

I appreciate your suggestion.

**Comment by bounin** [comment]
You solution is still having two problems comparing to mine
1. You still having leak if using "superblock". Every time you call _supermethodOfCurrentBlock_ in case you have superblock you create extra reference to superblock by calling _imp_impementationWithBlock(superblock)_. You can easily test this assigning two blocks on the same method and in second block calling supermethodOfCurrentBlock. In this case the first block is never released along with all captured objects. Similar situation when removing block with existing superblock you re-assigning method to implementation of superblock by calling _imp_implementationWithBlock(superblock)_. That creates again extra reference to superblock.
2. When you release block manually instead of calling imp_removeBlock it's probably creates some situation of crash if system later on internally will try to remove implementation for block. The main rule is every _imp_implementationWithBlock()_ should be balanced with _imp_removeBlock()_ to correctly release block. The expression imp_removeBlock(imp_implementationWithBlock(block)) does nothing as it just creates another retain and immediately release it without affecting current block retain status.

**Comment by zuccoi** [comment]
Thank you for your information. I'll fix it. If I failed to fix it with block-manage manner, I'll merge your pull requests.

**Comment by zuccoi** [comment]
I merged you pull request. Thanks a lot.

**Pull request closed without merging**
